# Server host/interface to bind to. Default is empty ("") to bind all interfaces (IPv4 + IPv6).
# Use "127.0.0.1" or "localhost" to restrict access to local machine only.
host: ""

# Server port
port: 8317

# TLS settings for HTTPS. When enabled, the server listens with the provided certificate and key.
tls:
  enable: false
  cert: ""
  key: ""

# Management API settings
remote-management:
  allow-remote: false
  secret-key: ""
  disable-control-panel: false
  panel-github-repository: "https://github.com/router-for-me/Cli-Proxy-API-Management-Center"

# Authentication directory (supports ~ for home directory)
auth-dir: "~/.cli-proxy-api"

# API keys for authentication
api-keys:
  - "haimichenha"
  - "linuxDo"

# Enable debug logging
debug: true

pprof:
  enable: false
  addr: "127.0.0.1:8316"

commercial-mode: false
logging-to-file: true
logs-max-total-size-mb: 0
error-logs-max-files: 10
usage-statistics-enabled: false

# Proxy URL. Supports socks5/http/https protocols.
proxy-url: ""

force-model-prefix: false
request-retry: 3
max-retry-interval: 30

quota-exceeded:
  switch-project: true
  switch-preview-model: true

routing:
  strategy: "round-robin"

ws-auth: false
nonstream-keepalive-interval: 0

# streaming:
#   keepalive-seconds: 15
#   bootstrap-retries: 1

# ============================================================
# Claude API keys (Anthropic format upstream: /v1/messages)
# ============================================================
claude-api-key:
  - api-key: "sk-K1KqwBtD3GBVeG4LwJqmUTEyOxiw6m9ZaLxr8ULTBCcB7rwz"
    base-url: "https://anyrouter.top"
    cloak:
      mode: "always"
    models:
      - name: "claude-opus-4-5-20251101"
        alias: "anyrouterclaude-opus-4-5"
      - name: "claude-haiku-4-5-20251001"
        alias: "anyrouterclaude-haiku-4-5"
      - name: "claude-opus-4-6"
        alias: "anyrouterclaude-opus-4-6"

  - api-key: "sk-pH7jCaocIbEbinneux3bgmGnk0hV8ftvW7ZCjRJCoBw9uj28"
    base-url: "https://wzw.pp.ua"
    cloak:
      mode: "always"
    models:
      - name: "claude-opus-4-5-20251101"
        alias: "wongclaude-opus-4-5-20251101"
      - name: "claude-opus-4-5"
        alias: "wongclaude-opus-4-5"
      - name: "claude-opus-4-6"
        alias: "wongclaude-opus-4-6"

    

# ============================================================
# OpenAI compatibility providers (OpenAI format upstream: /v1/chat/completions)
# ============================================================
openai-compatibility:
  - name: "feisakura"
    base-url: "https://api.feisakura.fun/v1"
    api-key-entries:
      - api-key: "sk-KtxnuaX7AWOOk2SDSuYJQ4lkw8h79fTsHqs4GxY5R5Ssi3S6"
    models:
      - name: "claude-opus-4-5-20251101"
        alias: "xyclaude-opus-4-5"
      - name: "claude-opus-4-6"
        alias: "xyclaude-opus-4-6"
      - name: "claude-opus-4-6-20260205"
        alias: "xyclaude-opus-4-6-20260205"

   - name: "kfc"
    base-url: "https://kfc-api.kyx03.de"
    api-key-entries:
      - api-key: "sk-hrznz62Miv83blM3YdBas7YthFrVqVd5xCdAUowzwPYVZIti"    
    models:
      - name: "gpt-5.3-codex-xhigh"
        alias: "kfcgpt-5.3-codex-xhigh"
      - name: "gpt-5.3-codex"
        alias: "kfcgpt-5.3-codex"
      - name: "gpt-5.2-xhigh"
        alias: "kfcgpt-5.2-xhigh"
      - name: "gpt-5.2-codex-xhigh"
        alias: "kfcgpt-5.2-codex-xhigh"
        
    - name: "bohe"
    base-url: "https://x666.me"
    api-key-entries:
      - api-key: "sk-wT2gX2xM1S1uSeNFjTOL1UBxoHah8sI1wP2IOp1ORW6S8X7p"      
      models:
        - name: "gpt-5.3-codex"
          alias: "bhgpt-5.3-codex"
        - name: "gpt-5.2-high"
          alias: "bhgpt-5.2-high"
        - name: "gpt-5.2-codex"
          alias: "bhgpt-5.2-codex"


# ============================================================
# Codex API keys (Codex format upstream: /v1/responses)
# ============================================================
# codex-api-key:
#   - api-key: "sk-hrznz62Miv83blM3YdBas7YthFrVqVd5xCdAUowzwPYVZIti"
#     base-url: "https://kfc-api.kyx03.de"
#     models:
#       - name: "gpt-5.3-codex-xhigh"
#         alias: "kfcgpt-5.3-codex-xhigh"
#       - name: "gpt-5.3-codex"
#         alias: "kfcgpt-5.3-codex"
#       - name: "gpt-5.2-xhigh"
#         alias: "kfcgpt-5.2-xhigh"
#       - name: "gpt-5.2-codex-xhigh"
#         alias: "kfcgpt-5.2-codex-xhigh"

#   - api-key: "sk-wT2gX2xM1S1uSeNFjTOL1UBxoHah8sI1wP2IOp1ORW6S8X7p"
#     base-url: "https://x666.me"
#     models:
#       - name: "gpt-5.3-codex"
#         alias: "bhgpt-5.3-codex"
#       - name: "gpt-5.2-high"
#         alias: "bhgpt-5.2-high"
#       - name: "gpt-5.2-codex"
#         alias: "bhgpt-5.2-codex"
# ============================================================
# OAuth model aliases
# ============================================================
oauth-model-alias:
  antigravity:
    - name: "rev19-uic3-1p"
      alias: "gemini-2.5-computer-use-preview-10-2025"
    - name: "gemini-3-pro-image"
      alias: "gemini-3-pro-image-preview"
    - name: "gemini-3-pro-high"
      alias: "gemini-3-pro-preview"
    - name: "gemini-3-flash"
      alias: "gemini-3-flash-preview"
    - name: "claude-sonnet-4-5"
      alias: "gemini-claude-sonnet-4-5"
    - name: "claude-sonnet-4-5-thinking"
      alias: "gemini-claude-sonnet-4-5-thinking"
    - name: "claude-opus-4-5-thinking"
      alias: "gemini-claude-opus-4-5-thinking"
